POST http://localhost:3001/reports
Content-Type: application/json

{
	"date": "1994-09-16",
	"description": "Fundação concluída",
	"site": "OBRA-001",
	"weather": "Ensolarado",
	"workers": ["Carlos", "Marta"]
}

###

GET http://localhost:3001/reports
Content-Type: application/json

###

GET http://localhost:3001/reports/6d6ff26e-6187-41b2-998c-36383cef3bae
Content-Type: application/json

###

PUT http://localhost:3001/reports/0a74b213-6b60-4266-bbee-e8323648c824
Content-Type: application/json

{
	"date": "1994-09-17",
	"description": "Fundação finalizada",
	"site": "OBRA-001",
	"weather": "Chuvoso",
	"workers": ["Carlos", "Marta"]
}
